import Image from 'next/image';
import Link from 'next/link';
import React from 'react';
import { twMerge } from 'tailwind-merge';

import arrowIcon from '../../../../public/images/Icons/arrow-sm-45.svg';
import { AprLpChart } from '../global/Apr/AprLpChart';
import ALPHeader from './ALPHeader';

export default function ALPDetails({ className }: { className?: string }) {
  return (
    <div className={twMerge(className, 'flex flex-col gap-3')}>
      <ALPHeader />

      <div>
        <div className="flex flex-col gap-3 p-4 border rounded-xl">
          <div className="flex flex-col justify-between">
            <div>
              <p className="text-sm opacity-75">
                The liquidity pool serves as the counterparty for traders,
                supplying the assets needed when users open leveraged positions.
                Essentially, traders borrow tokens to execute their trades, and
                pay fees for the service.
              </p>

              <p className="text-sm opacity-75 mt-4">
                <span className="font-interSemibold">The ALP token</span>{' '}
                represents shares of said pool, and its value is backed by:
              </p>

              <ul>
                <li className="text-sm opacity-75 list-disc ml-4 mt-1">
                  A diversified index fund comprising{' '}
                  <span className="font-interSemibold">
                    JitoSOL, BONK, WBTC and USDC
                  </span>
                  .
                </li>
                <li className="text-sm opacity-75 list-disc ml-4 mt-1">
                  The net{' '}
                  <span className="font-interSemibold">profit and loss</span> of
                  traders within the ecosystem.
                </li>
                <li className="text-sm opacity-75 list-disc ml-4 mt-1">
                  <span className="font-interSemibold">70% of all fees</span>{' '}
                  generated by the pool, including:
                  <ul className="flex flex-col gap-1">
                    <li className="text-sm list-disc ml-4 mt-1">
                      Opening & closing fees
                    </li>
                    <li className="text-sm list-disc ml-4 mt-1">
                      Borrowing fees
                    </li>
                    <li className="text-sm list-disc ml-4 mt-1">
                      ALP minting and redeeming fees
                    </li>
                  </ul>
                </li>
              </ul>

              <p className="text-sm opacity-75 mt-4">
                This structure ensures ALP token holders benefit from both the
                pool&apos;s underlying assets and its trading activity.
              </p>

              <p className="text-sm font-interMedium mt-2 bg-[linear-gradient(110deg,#5AA6FA_40%,#B9EEFF_60%,#5AA6FA)] animate-text-shimmer bg-clip-text text-transparent bg-[length:250%_100%]">
                All fees continuously accrue in the pool when each trade closes.
              </p>

              <p className="text-sm font-interMedium mt-2 bg-[linear-gradient(110deg,#5AA6FA_40%,#B9EEFF_60%,#5AA6FA)] animate-text-shimmer bg-clip-text text-transparent bg-[length:250%_100%]">
                LPers also benefit from JitoSOL native yield.
              </p>
            </div>
          </div>

          <div className="w-full h-[15em] -mb-5">
            <AprLpChart isSmallScreen={false} isAlpPage />
          </div>

          <Link
            href="https://docs.adrena.xyz/tokenomics/alp"
            target="_blank"
            rel="noopener noreferrer"
            className="w-fit opacity-50 hover:opacity-100 transition-opacity duration-300 flex flex-row gap-2 items-center mt-3 cursor-pointer"
          >
            <p className="text-sm">Learn more</p>
            <Image src={arrowIcon} alt="arrow icon" className="w-2 h-2" />
          </Link>
        </div>
      </div>
    </div>
  );
}
